import type { Country } from "@dorfpartys/shared";

export interface BundeslandSeed {
  slug: string;
  name: string;
  country: Country;
  kreise: Array<{ slug: string; name: string }>;
}

// Vollständiger Bundesland/Kreis-Import für DE/AT/CH (AGENTS.md Abschnitt 10).
// Quelle: Namen und Gebietsstand orientieren sich an den Standard-Verwaltungsgliederungen
// von Destatis (Kreise/kreisfreie Städte, DE), Statistik Austria (politische Bezirke,
// inkl. Statutarstädte, AT) und dem Bundesamt für Statistik / BFS (Kantone und Bezirke/
// Wahlkreise/Amtsbezirke, CH), Wissensstand zum Modell-Trainingsschnitt. Gebietsreformen
// (Gemeinde-/Kreisfusionen, Bezirksauflösungen) kommen gelegentlich vor — bei Bedarf
// periodisch gegen die jeweilige amtliche Quelle abgleichen und aktualisieren.
//
// Kreis-Slugs sind global eindeutig (DB-Unique-Constraint über die gesamte
// Slug-Registry, AGENTS.md 1.5) und kollidieren nicht mit Party-Art- oder
// Monats-Slugs. Wo Namen bundeslandübergreifend identisch slugifizieren würden
// (z.B. mehrere "Landkreis"/"Stadt"-Paare gleichen Namens), wurde der
// Bundesland-/Kantons-Slug als Suffix angehängt.
//
// Sonderfälle:
// - Berlin, Hamburg: Bezirke als Kreis-Ebene verwendet (Berlin 12, Hamburg 7).
// - Bremen: Zwei-Städte-Gliederung (Bremen/Bremerhaven) als Kreis-Ebene.
// - Wien (AT): keine Bezirksebene unterhalb des Bundeslands in dieser Taxonomie (Wien
//   ist zugleich Land und Gemeinde) — `kreise: []`, wie auch für Kantone ohne
//   Bezirks-/Distriktebene (z.B. Zug, Glarus, Basel-Stadt, Appenzell A.Rh./I.Rh.).
export const BUNDESLAND_SEED: BundeslandSeed[] = [
  {
    slug: "schleswig-holstein",
    name: "Schleswig-Holstein",
    country: "de",
    kreise: [
      { slug: "flensburg", name: "Flensburg" },
      { slug: "kiel", name: "Kiel" },
      { slug: "luebeck", name: "Lübeck" },
      { slug: "neumuenster", name: "Neumünster" },
      { slug: "dithmarschen", name: "Dithmarschen" },
      { slug: "herzogtum-lauenburg", name: "Herzogtum Lauenburg" },
      { slug: "nordfriesland", name: "Nordfriesland" },
      { slug: "ostholstein", name: "Ostholstein" },
      { slug: "pinneberg", name: "Pinneberg" },
      { slug: "ploen", name: "Plön" },
      { slug: "rendsburg-eckernfoerde", name: "Rendsburg-Eckernförde" },
      { slug: "schleswig-flensburg", name: "Schleswig-Flensburg" },
      { slug: "segeberg", name: "Segeberg" },
      { slug: "steinburg", name: "Steinburg" },
      { slug: "stormarn", name: "Stormarn" },
    ],
  },
  {
    slug: "hamburg",
    name: "Hamburg",
    country: "de",
    kreise: [
      { slug: "hamburg-mitte", name: "Hamburg-Mitte" },
      { slug: "altona", name: "Altona" },
      { slug: "eimsbuettel", name: "Eimsbüttel" },
      { slug: "hamburg-nord", name: "Hamburg-Nord" },
      { slug: "wandsbek", name: "Wandsbek" },
      { slug: "bergedorf", name: "Bergedorf" },
      { slug: "harburg", name: "Harburg" },
    ],
  },
  {
    slug: "niedersachsen",
    name: "Niedersachsen",
    country: "de",
    kreise: [
      { slug: "braunschweig", name: "Braunschweig" },
      { slug: "delmenhorst", name: "Delmenhorst" },
      { slug: "emden", name: "Emden" },
      { slug: "oldenburg-stadt", name: "Oldenburg (Stadt)" },
      { slug: "osnabrueck-stadt", name: "Osnabrück (Stadt)" },
      { slug: "salzgitter", name: "Salzgitter" },
      { slug: "wilhelmshaven", name: "Wilhelmshaven" },
      { slug: "wolfsburg", name: "Wolfsburg" },
      { slug: "region-hannover", name: "Region Hannover" },
      { slug: "ammerland", name: "Ammerland" },
      { slug: "aurich", name: "Aurich" },
      { slug: "celle", name: "Celle" },
      { slug: "cloppenburg", name: "Cloppenburg" },
      { slug: "cuxhaven", name: "Cuxhaven" },
      { slug: "diepholz", name: "Diepholz" },
      { slug: "emsland", name: "Emsland" },
      { slug: "friesland", name: "Friesland" },
      { slug: "gifhorn", name: "Gifhorn" },
      { slug: "goslar", name: "Goslar" },
      { slug: "goettingen", name: "Göttingen" },
      { slug: "grafschaft-bentheim", name: "Grafschaft Bentheim" },
      { slug: "hameln-pyrmont", name: "Hameln-Pyrmont" },
      { slug: "harburg-landkreis", name: "Harburg (Landkreis)" },
      { slug: "heidekreis", name: "Heidekreis" },
      { slug: "helmstedt", name: "Helmstedt" },
      { slug: "hildesheim", name: "Hildesheim" },
      { slug: "holzminden", name: "Holzminden" },
      { slug: "leer", name: "Leer" },
      { slug: "luechow-dannenberg", name: "Lüchow-Dannenberg" },
      { slug: "lueneburg", name: "Lüneburg" },
      { slug: "nienburg-weser", name: "Nienburg/Weser" },
      { slug: "northeim", name: "Northeim" },
      { slug: "oldenburg-landkreis", name: "Oldenburg (Landkreis)" },
      { slug: "osnabrueck-landkreis", name: "Osnabrück (Landkreis)" },
      { slug: "osterholz", name: "Osterholz" },
      { slug: "peine", name: "Peine" },
      { slug: "rotenburg-wuemme", name: "Rotenburg (Wümme)" },
      { slug: "schaumburg", name: "Schaumburg" },
      { slug: "stade", name: "Stade" },
      { slug: "uelzen", name: "Uelzen" },
      { slug: "vechta", name: "Vechta" },
      { slug: "verden", name: "Verden" },
      { slug: "wesermarsch", name: "Wesermarsch" },
      { slug: "wittmund", name: "Wittmund" },
      { slug: "wolfenbuettel", name: "Wolfenbüttel" },
    ],
  },
  {
    slug: "bremen",
    name: "Bremen",
    country: "de",
    kreise: [
      { slug: "bremen-stadt", name: "Bremen (Stadt)" },
      { slug: "bremerhaven", name: "Bremerhaven" },
    ],
  },
  {
    slug: "nordrhein-westfalen",
    name: "Nordrhein-Westfalen",
    country: "de",
    kreise: [
      { slug: "bielefeld", name: "Bielefeld" },
      { slug: "bochum", name: "Bochum" },
      { slug: "bonn", name: "Bonn" },
      { slug: "bottrop", name: "Bottrop" },
      { slug: "dortmund", name: "Dortmund" },
      { slug: "duisburg", name: "Duisburg" },
      { slug: "duesseldorf", name: "Düsseldorf" },
      { slug: "essen", name: "Essen" },
      { slug: "gelsenkirchen", name: "Gelsenkirchen" },
      { slug: "hagen", name: "Hagen" },
      { slug: "hamm", name: "Hamm" },
      { slug: "herne", name: "Herne" },
      { slug: "koeln", name: "Köln" },
      { slug: "krefeld", name: "Krefeld" },
      { slug: "leverkusen", name: "Leverkusen" },
      { slug: "moenchengladbach", name: "Mönchengladbach" },
      { slug: "muelheim-an-der-ruhr", name: "Mülheim an der Ruhr" },
      { slug: "muenster", name: "Münster" },
      { slug: "oberhausen", name: "Oberhausen" },
      { slug: "remscheid", name: "Remscheid" },
      { slug: "solingen", name: "Solingen" },
      { slug: "wuppertal", name: "Wuppertal" },
      { slug: "staedteregion-aachen", name: "Städteregion Aachen" },
      { slug: "borken", name: "Borken" },
      { slug: "coesfeld", name: "Coesfeld" },
      { slug: "dueren", name: "Düren" },
      { slug: "ennepe-ruhr-kreis", name: "Ennepe-Ruhr-Kreis" },
      { slug: "euskirchen", name: "Euskirchen" },
      { slug: "guetersloh", name: "Gütersloh" },
      { slug: "heinsberg", name: "Heinsberg" },
      { slug: "herford", name: "Herford" },
      { slug: "hochsauerlandkreis", name: "Hochsauerlandkreis" },
      { slug: "hoexter", name: "Höxter" },
      { slug: "kleve", name: "Kleve" },
      { slug: "lippe", name: "Lippe" },
      { slug: "maerkischer-kreis", name: "Märkischer Kreis" },
      { slug: "mettmann", name: "Mettmann" },
      { slug: "minden-luebbecke", name: "Minden-Lübbecke" },
      { slug: "oberbergischer-kreis", name: "Oberbergischer Kreis" },
      { slug: "olpe", name: "Olpe" },
      { slug: "paderborn", name: "Paderborn" },
      { slug: "recklinghausen", name: "Recklinghausen" },
      { slug: "rhein-erft-kreis", name: "Rhein-Erft-Kreis" },
      { slug: "rhein-kreis-neuss", name: "Rhein-Kreis Neuss" },
      {
        slug: "rheinisch-bergischer-kreis",
        name: "Rheinisch-Bergischer Kreis",
      },
      { slug: "rhein-sieg-kreis", name: "Rhein-Sieg-Kreis" },
      { slug: "siegen-wittgenstein", name: "Siegen-Wittgenstein" },
      { slug: "soest", name: "Soest" },
      { slug: "steinfurt", name: "Steinfurt" },
      { slug: "unna", name: "Unna" },
      { slug: "viersen", name: "Viersen" },
      { slug: "warendorf", name: "Warendorf" },
      { slug: "wesel", name: "Wesel" },
    ],
  },
  {
    slug: "hessen",
    name: "Hessen",
    country: "de",
    kreise: [
      { slug: "darmstadt", name: "Darmstadt" },
      { slug: "frankfurt-am-main", name: "Frankfurt am Main" },
      { slug: "kassel-stadt", name: "Kassel (Stadt)" },
      { slug: "offenbach-am-main", name: "Offenbach am Main" },
      { slug: "wiesbaden", name: "Wiesbaden" },
      { slug: "bergstrasse", name: "Bergstraße" },
      { slug: "darmstadt-dieburg", name: "Darmstadt-Dieburg" },
      { slug: "fulda", name: "Fulda" },
      { slug: "giessen", name: "Gießen" },
      { slug: "gross-gerau", name: "Groß-Gerau" },
      { slug: "hersfeld-rotenburg", name: "Hersfeld-Rotenburg" },
      { slug: "hochtaunuskreis", name: "Hochtaunuskreis" },
      { slug: "kassel-landkreis", name: "Kassel (Landkreis)" },
      { slug: "lahn-dill-kreis", name: "Lahn-Dill-Kreis" },
      { slug: "limburg-weilburg", name: "Limburg-Weilburg" },
      { slug: "main-kinzig-kreis", name: "Main-Kinzig-Kreis" },
      { slug: "main-taunus-kreis", name: "Main-Taunus-Kreis" },
      { slug: "marburg-biedenkopf", name: "Marburg-Biedenkopf" },
      { slug: "odenwaldkreis", name: "Odenwaldkreis" },
      { slug: "offenbach-landkreis", name: "Offenbach (Landkreis)" },
      { slug: "rheingau-taunus-kreis", name: "Rheingau-Taunus-Kreis" },
      { slug: "schwalm-eder-kreis", name: "Schwalm-Eder-Kreis" },
      { slug: "vogelsbergkreis", name: "Vogelsbergkreis" },
      { slug: "waldeck-frankenberg", name: "Waldeck-Frankenberg" },
      { slug: "werra-meissner-kreis", name: "Werra-Meißner-Kreis" },
      { slug: "wetteraukreis", name: "Wetteraukreis" },
    ],
  },
  {
    slug: "rheinland-pfalz",
    name: "Rheinland-Pfalz",
    country: "de",
    kreise: [
      { slug: "frankenthal-pfalz", name: "Frankenthal (Pfalz)" },
      { slug: "kaiserslautern-stadt", name: "Kaiserslautern (Stadt)" },
      { slug: "koblenz", name: "Koblenz" },
      { slug: "landau-in-der-pfalz", name: "Landau in der Pfalz" },
      { slug: "ludwigshafen-am-rhein", name: "Ludwigshafen am Rhein" },
      { slug: "mainz", name: "Mainz" },
      {
        slug: "neustadt-an-der-weinstrasse",
        name: "Neustadt an der Weinstraße",
      },
      { slug: "pirmasens", name: "Pirmasens" },
      { slug: "speyer", name: "Speyer" },
      { slug: "trier-stadt", name: "Trier (Stadt)" },
      { slug: "worms", name: "Worms" },
      { slug: "zweibruecken", name: "Zweibrücken" },
      { slug: "ahrweiler", name: "Ahrweiler" },
      { slug: "altenkirchen-westerwald", name: "Altenkirchen (Westerwald)" },
      { slug: "alzey-worms", name: "Alzey-Worms" },
      { slug: "bad-duerkheim", name: "Bad Dürkheim" },
      { slug: "bad-kreuznach", name: "Bad Kreuznach" },
      { slug: "bernkastel-wittlich", name: "Bernkastel-Wittlich" },
      { slug: "birkenfeld", name: "Birkenfeld" },
      { slug: "cochem-zell", name: "Cochem-Zell" },
      { slug: "donnersbergkreis", name: "Donnersbergkreis" },
      { slug: "eifelkreis-bitburg-pruem", name: "Eifelkreis Bitburg-Prüm" },
      { slug: "germersheim", name: "Germersheim" },
      { slug: "kaiserslautern-landkreis", name: "Kaiserslautern (Landkreis)" },
      { slug: "kusel", name: "Kusel" },
      { slug: "mainz-bingen", name: "Mainz-Bingen" },
      { slug: "mayen-koblenz", name: "Mayen-Koblenz" },
      { slug: "neuwied", name: "Neuwied" },
      { slug: "rhein-hunsrueck-kreis", name: "Rhein-Hunsrück-Kreis" },
      { slug: "rhein-lahn-kreis", name: "Rhein-Lahn-Kreis" },
      { slug: "rhein-pfalz-kreis", name: "Rhein-Pfalz-Kreis" },
      { slug: "suedliche-weinstrasse", name: "Südliche Weinstraße" },
      { slug: "suedwestpfalz", name: "Südwestpfalz" },
      { slug: "trier-saarburg", name: "Trier-Saarburg" },
      { slug: "vulkaneifel", name: "Vulkaneifel" },
      { slug: "westerwaldkreis", name: "Westerwaldkreis" },
    ],
  },
  {
    slug: "baden-wuerttemberg",
    name: "Baden-Württemberg",
    country: "de",
    kreise: [
      { slug: "baden-baden", name: "Baden-Baden" },
      { slug: "freiburg-im-breisgau", name: "Freiburg im Breisgau" },
      { slug: "heidelberg", name: "Heidelberg" },
      { slug: "heilbronn-stadt", name: "Heilbronn (Stadt)" },
      { slug: "karlsruhe-stadt", name: "Karlsruhe (Stadt)" },
      { slug: "mannheim", name: "Mannheim" },
      { slug: "pforzheim", name: "Pforzheim" },
      { slug: "stuttgart", name: "Stuttgart" },
      { slug: "ulm", name: "Ulm" },
      { slug: "alb-donau-kreis", name: "Alb-Donau-Kreis" },
      { slug: "biberach", name: "Biberach" },
      { slug: "boeblingen", name: "Böblingen" },
      { slug: "bodenseekreis", name: "Bodenseekreis" },
      { slug: "breisgau-hochschwarzwald", name: "Breisgau-Hochschwarzwald" },
      { slug: "calw", name: "Calw" },
      { slug: "emmendingen", name: "Emmendingen" },
      { slug: "enzkreis", name: "Enzkreis" },
      { slug: "esslingen", name: "Esslingen" },
      { slug: "freudenstadt", name: "Freudenstadt" },
      { slug: "goeppingen", name: "Göppingen" },
      { slug: "heidenheim", name: "Heidenheim" },
      { slug: "heilbronn-landkreis", name: "Heilbronn (Landkreis)" },
      { slug: "hohenlohekreis", name: "Hohenlohekreis" },
      { slug: "karlsruhe-landkreis", name: "Karlsruhe (Landkreis)" },
      { slug: "konstanz", name: "Konstanz" },
      { slug: "loerrach", name: "Lörrach" },
      { slug: "ludwigsburg", name: "Ludwigsburg" },
      { slug: "main-tauber-kreis", name: "Main-Tauber-Kreis" },
      { slug: "neckar-odenwald-kreis", name: "Neckar-Odenwald-Kreis" },
      { slug: "ortenaukreis", name: "Ortenaukreis" },
      { slug: "ostalbkreis", name: "Ostalbkreis" },
      { slug: "rastatt", name: "Rastatt" },
      { slug: "ravensburg", name: "Ravensburg" },
      { slug: "rems-murr-kreis", name: "Rems-Murr-Kreis" },
      { slug: "reutlingen", name: "Reutlingen" },
      { slug: "rhein-neckar-kreis", name: "Rhein-Neckar-Kreis" },
      { slug: "rottweil", name: "Rottweil" },
      { slug: "schwaebisch-hall", name: "Schwäbisch Hall" },
      { slug: "schwarzwald-baar-kreis", name: "Schwarzwald-Baar-Kreis" },
      { slug: "sigmaringen", name: "Sigmaringen" },
      { slug: "tuebingen", name: "Tübingen" },
      { slug: "tuttlingen", name: "Tuttlingen" },
      { slug: "waldshut", name: "Waldshut" },
      { slug: "zollernalbkreis", name: "Zollernalbkreis" },
    ],
  },
  {
    slug: "bayern",
    name: "Bayern",
    country: "de",
    kreise: [
      { slug: "amberg", name: "Amberg" },
      { slug: "ansbach-stadt", name: "Ansbach (Stadt)" },
      { slug: "aschaffenburg-stadt", name: "Aschaffenburg (Stadt)" },
      { slug: "augsburg-stadt", name: "Augsburg (Stadt)" },
      { slug: "bamberg-stadt", name: "Bamberg (Stadt)" },
      { slug: "bayreuth-stadt", name: "Bayreuth (Stadt)" },
      { slug: "coburg-stadt", name: "Coburg (Stadt)" },
      { slug: "erlangen", name: "Erlangen" },
      { slug: "fuerth-stadt", name: "Fürth (Stadt)" },
      { slug: "hof-stadt", name: "Hof (Stadt)" },
      { slug: "ingolstadt", name: "Ingolstadt" },
      { slug: "kaufbeuren", name: "Kaufbeuren" },
      { slug: "kempten-allgaeu", name: "Kempten (Allgäu)" },
      { slug: "landshut-stadt", name: "Landshut (Stadt)" },
      { slug: "memmingen", name: "Memmingen" },
      { slug: "muenchen-stadt", name: "München (Stadt)" },
      { slug: "nuernberg", name: "Nürnberg" },
      { slug: "passau-stadt", name: "Passau (Stadt)" },
      { slug: "regensburg-stadt", name: "Regensburg (Stadt)" },
      { slug: "rosenheim-stadt", name: "Rosenheim (Stadt)" },
      { slug: "schwabach", name: "Schwabach" },
      { slug: "schweinfurt-stadt", name: "Schweinfurt (Stadt)" },
      { slug: "straubing", name: "Straubing" },
      { slug: "weiden-in-der-oberpfalz", name: "Weiden in der Oberpfalz" },
      { slug: "wuerzburg-stadt", name: "Würzburg (Stadt)" },
      { slug: "aichach-friedberg", name: "Aichach-Friedberg" },
      { slug: "altoetting", name: "Altötting" },
      { slug: "amberg-sulzbach", name: "Amberg-Sulzbach" },
      { slug: "ansbach-landkreis", name: "Ansbach (Landkreis)" },
      { slug: "aschaffenburg-landkreis", name: "Aschaffenburg (Landkreis)" },
      { slug: "augsburg-landkreis", name: "Augsburg (Landkreis)" },
      { slug: "bad-kissingen", name: "Bad Kissingen" },
      { slug: "bad-toelz-wolfratshausen", name: "Bad Tölz-Wolfratshausen" },
      { slug: "bamberg-landkreis", name: "Bamberg (Landkreis)" },
      { slug: "bayreuth-landkreis", name: "Bayreuth (Landkreis)" },
      { slug: "berchtesgadener-land", name: "Berchtesgadener Land" },
      { slug: "cham", name: "Cham" },
      { slug: "coburg-landkreis", name: "Coburg (Landkreis)" },
      { slug: "dachau", name: "Dachau" },
      { slug: "deggendorf", name: "Deggendorf" },
      { slug: "dillingen-an-der-donau", name: "Dillingen an der Donau" },
      { slug: "dingolfing-landau", name: "Dingolfing-Landau" },
      { slug: "donau-ries", name: "Donau-Ries" },
      { slug: "ebersberg", name: "Ebersberg" },
      { slug: "eichstaett", name: "Eichstätt" },
      { slug: "erding", name: "Erding" },
      { slug: "erlangen-hoechstadt", name: "Erlangen-Höchstadt" },
      { slug: "forchheim", name: "Forchheim" },
      { slug: "freising", name: "Freising" },
      { slug: "freyung-grafenau", name: "Freyung-Grafenau" },
      { slug: "fuerstenfeldbruck", name: "Fürstenfeldbruck" },
      { slug: "fuerth-landkreis", name: "Fürth (Landkreis)" },
      { slug: "garmisch-partenkirchen", name: "Garmisch-Partenkirchen" },
      { slug: "guenzburg", name: "Günzburg" },
      { slug: "hassberge", name: "Haßberge" },
      { slug: "hof-landkreis", name: "Hof (Landkreis)" },
      { slug: "kelheim", name: "Kelheim" },
      { slug: "kitzingen", name: "Kitzingen" },
      { slug: "kronach", name: "Kronach" },
      { slug: "kulmbach", name: "Kulmbach" },
      { slug: "landsberg-am-lech", name: "Landsberg am Lech" },
      { slug: "landshut-landkreis", name: "Landshut (Landkreis)" },
      { slug: "lichtenfels", name: "Lichtenfels" },
      { slug: "lindau-bodensee", name: "Lindau (Bodensee)" },
      { slug: "main-spessart", name: "Main-Spessart" },
      { slug: "miesbach", name: "Miesbach" },
      { slug: "miltenberg", name: "Miltenberg" },
      { slug: "muehldorf-am-inn", name: "Mühldorf am Inn" },
      { slug: "muenchen-landkreis", name: "München (Landkreis)" },
      { slug: "neuburg-schrobenhausen", name: "Neuburg-Schrobenhausen" },
      { slug: "neumarkt-in-der-oberpfalz", name: "Neumarkt in der Oberpfalz" },
      {
        slug: "neustadt-an-der-aisch-bad-windsheim",
        name: "Neustadt an der Aisch-Bad Windsheim",
      },
      { slug: "neustadt-an-der-waldnaab", name: "Neustadt an der Waldnaab" },
      { slug: "neu-ulm", name: "Neu-Ulm" },
      { slug: "nuernberger-land", name: "Nürnberger Land" },
      { slug: "oberallgaeu", name: "Oberallgäu" },
      { slug: "ostallgaeu", name: "Ostallgäu" },
      { slug: "passau-landkreis", name: "Passau (Landkreis)" },
      { slug: "pfaffenhofen-an-der-ilm", name: "Pfaffenhofen an der Ilm" },
      { slug: "regen", name: "Regen" },
      { slug: "regensburg-landkreis", name: "Regensburg (Landkreis)" },
      { slug: "rhoen-grabfeld", name: "Rhön-Grabfeld" },
      { slug: "rosenheim-landkreis", name: "Rosenheim (Landkreis)" },
      { slug: "roth", name: "Roth" },
      { slug: "rottal-inn", name: "Rottal-Inn" },
      { slug: "schwandorf", name: "Schwandorf" },
      { slug: "schweinfurt-landkreis", name: "Schweinfurt (Landkreis)" },
      { slug: "starnberg", name: "Starnberg" },
      { slug: "straubing-bogen", name: "Straubing-Bogen" },
      { slug: "tirschenreuth", name: "Tirschenreuth" },
      { slug: "traunstein", name: "Traunstein" },
      { slug: "unterallgaeu", name: "Unterallgäu" },
      { slug: "weilheim-schongau", name: "Weilheim-Schongau" },
      { slug: "weissenburg-gunzenhausen", name: "Weißenburg-Gunzenhausen" },
      {
        slug: "wunsiedel-im-fichtelgebirge",
        name: "Wunsiedel im Fichtelgebirge",
      },
      { slug: "wuerzburg-landkreis", name: "Würzburg (Landkreis)" },
    ],
  },
  {
    slug: "saarland",
    name: "Saarland",
    country: "de",
    kreise: [
      {
        slug: "regionalverband-saarbruecken",
        name: "Regionalverband Saarbrücken",
      },
      { slug: "merzig-wadern", name: "Merzig-Wadern" },
      { slug: "neunkirchen", name: "Neunkirchen" },
      { slug: "saarlouis", name: "Saarlouis" },
      { slug: "saarpfalz-kreis", name: "Saarpfalz-Kreis" },
      { slug: "st-wendel", name: "St. Wendel" },
    ],
  },
  {
    slug: "berlin",
    name: "Berlin",
    country: "de",
    kreise: [
      { slug: "mitte", name: "Mitte" },
      { slug: "friedrichshain-kreuzberg", name: "Friedrichshain-Kreuzberg" },
      { slug: "pankow", name: "Pankow" },
      {
        slug: "charlottenburg-wilmersdorf",
        name: "Charlottenburg-Wilmersdorf",
      },
      { slug: "spandau", name: "Spandau" },
      { slug: "steglitz-zehlendorf", name: "Steglitz-Zehlendorf" },
      { slug: "tempelhof-schoeneberg", name: "Tempelhof-Schöneberg" },
      { slug: "neukoelln", name: "Neukölln" },
      { slug: "treptow-koepenick", name: "Treptow-Köpenick" },
      { slug: "marzahn-hellersdorf", name: "Marzahn-Hellersdorf" },
      { slug: "lichtenberg", name: "Lichtenberg" },
      { slug: "reinickendorf", name: "Reinickendorf" },
    ],
  },
  {
    slug: "brandenburg",
    name: "Brandenburg",
    country: "de",
    kreise: [
      { slug: "brandenburg-an-der-havel", name: "Brandenburg an der Havel" },
      { slug: "cottbus", name: "Cottbus" },
      { slug: "frankfurt-oder", name: "Frankfurt (Oder)" },
      { slug: "potsdam", name: "Potsdam" },
      { slug: "barnim", name: "Barnim" },
      { slug: "dahme-spreewald", name: "Dahme-Spreewald" },
      { slug: "elbe-elster", name: "Elbe-Elster" },
      { slug: "havelland", name: "Havelland" },
      { slug: "maerkisch-oderland", name: "Märkisch-Oderland" },
      { slug: "oberhavel", name: "Oberhavel" },
      { slug: "oberspreewald-lausitz", name: "Oberspreewald-Lausitz" },
      { slug: "oder-spree", name: "Oder-Spree" },
      { slug: "ostprignitz-ruppin", name: "Ostprignitz-Ruppin" },
      { slug: "potsdam-mittelmark", name: "Potsdam-Mittelmark" },
      { slug: "prignitz", name: "Prignitz" },
      { slug: "spree-neisse", name: "Spree-Neiße" },
      { slug: "teltow-flaeming", name: "Teltow-Fläming" },
      { slug: "uckermark", name: "Uckermark" },
    ],
  },
  {
    slug: "mecklenburg-vorpommern",
    name: "Mecklenburg-Vorpommern",
    country: "de",
    kreise: [
      { slug: "rostock-stadt", name: "Rostock (Stadt)" },
      { slug: "schwerin", name: "Schwerin" },
      { slug: "landkreis-rostock", name: "Landkreis Rostock" },
      { slug: "ludwigslust-parchim", name: "Ludwigslust-Parchim" },
      {
        slug: "mecklenburgische-seenplatte",
        name: "Mecklenburgische Seenplatte",
      },
      { slug: "nordwestmecklenburg", name: "Nordwestmecklenburg" },
      { slug: "vorpommern-greifswald", name: "Vorpommern-Greifswald" },
      { slug: "vorpommern-ruegen", name: "Vorpommern-Rügen" },
    ],
  },
  {
    slug: "sachsen",
    name: "Sachsen",
    country: "de",
    kreise: [
      { slug: "chemnitz", name: "Chemnitz" },
      { slug: "dresden", name: "Dresden" },
      { slug: "leipzig-stadt", name: "Leipzig (Stadt)" },
      { slug: "bautzen", name: "Bautzen" },
      { slug: "erzgebirgskreis", name: "Erzgebirgskreis" },
      { slug: "goerlitz", name: "Görlitz" },
      { slug: "leipzig-landkreis", name: "Leipzig (Landkreis)" },
      { slug: "meissen", name: "Meißen" },
      { slug: "mittelsachsen", name: "Mittelsachsen" },
      { slug: "nordsachsen", name: "Nordsachsen" },
      {
        slug: "saechsische-schweiz-osterzgebirge",
        name: "Sächsische Schweiz-Osterzgebirge",
      },
      { slug: "vogtlandkreis", name: "Vogtlandkreis" },
      { slug: "zwickau", name: "Zwickau" },
    ],
  },
  {
    slug: "sachsen-anhalt",
    name: "Sachsen-Anhalt",
    country: "de",
    kreise: [
      { slug: "dessau-rosslau", name: "Dessau-Roßlau" },
      { slug: "halle-saale", name: "Halle (Saale)" },
      { slug: "magdeburg", name: "Magdeburg" },
      { slug: "altmarkkreis-salzwedel", name: "Altmarkkreis Salzwedel" },
      { slug: "anhalt-bitterfeld", name: "Anhalt-Bitterfeld" },
      { slug: "boerde", name: "Börde" },
      { slug: "burgenlandkreis", name: "Burgenlandkreis" },
      { slug: "harz", name: "Harz" },
      { slug: "jerichower-land", name: "Jerichower Land" },
      { slug: "mansfeld-suedharz", name: "Mansfeld-Südharz" },
      { slug: "saalekreis", name: "Saalekreis" },
      { slug: "salzlandkreis", name: "Salzlandkreis" },
      { slug: "stendal", name: "Stendal" },
      { slug: "wittenberg", name: "Wittenberg" },
    ],
  },
  {
    slug: "thueringen",
    name: "Thüringen",
    country: "de",
    kreise: [
      { slug: "erfurt", name: "Erfurt" },
      { slug: "gera", name: "Gera" },
      { slug: "jena", name: "Jena" },
      { slug: "suhl", name: "Suhl" },
      { slug: "weimar", name: "Weimar" },
      { slug: "altenburger-land", name: "Altenburger Land" },
      { slug: "eichsfeld", name: "Eichsfeld" },
      { slug: "gotha", name: "Gotha" },
      { slug: "greiz", name: "Greiz" },
      { slug: "hildburghausen", name: "Hildburghausen" },
      { slug: "ilm-kreis", name: "Ilm-Kreis" },
      { slug: "kyffhaeuserkreis", name: "Kyffhäuserkreis" },
      { slug: "nordhausen", name: "Nordhausen" },
      { slug: "saale-holzland-kreis", name: "Saale-Holzland-Kreis" },
      { slug: "saale-orla-kreis", name: "Saale-Orla-Kreis" },
      { slug: "saalfeld-rudolstadt", name: "Saalfeld-Rudolstadt" },
      { slug: "schmalkalden-meiningen", name: "Schmalkalden-Meiningen" },
      { slug: "soemmerda", name: "Sömmerda" },
      { slug: "sonneberg", name: "Sonneberg" },
      { slug: "unstrut-hainich-kreis", name: "Unstrut-Hainich-Kreis" },
      { slug: "wartburgkreis", name: "Wartburgkreis" },
      { slug: "weimarer-land", name: "Weimarer Land" },
    ],
  },
  {
    slug: "wien",
    name: "Wien",
    country: "at",
    kreise: [],
  },
  {
    slug: "niederoesterreich",
    name: "Niederösterreich",
    country: "at",
    kreise: [
      { slug: "krems-an-der-donau", name: "Krems an der Donau" },
      { slug: "st-poelten-stadt", name: "St. Pölten (Stadt)" },
      { slug: "waidhofen-an-der-ybbs", name: "Waidhofen an der Ybbs" },
      { slug: "wiener-neustadt-stadt", name: "Wiener Neustadt (Stadt)" },
      { slug: "amstetten", name: "Amstetten" },
      { slug: "baden", name: "Baden" },
      { slug: "bruck-an-der-leitha", name: "Bruck an der Leitha" },
      { slug: "gaenserndorf", name: "Gänserndorf" },
      { slug: "gmuend", name: "Gmünd" },
      { slug: "hollabrunn", name: "Hollabrunn" },
      { slug: "horn", name: "Horn" },
      { slug: "korneuburg", name: "Korneuburg" },
      { slug: "krems-land", name: "Krems (Land)" },
      { slug: "lilienfeld", name: "Lilienfeld" },
      { slug: "melk", name: "Melk" },
      { slug: "mistelbach", name: "Mistelbach" },
      { slug: "moedling", name: "Mödling" },
      { slug: "neunkirchen-niederoesterreich", name: "Neunkirchen" },
      { slug: "st-poelten-land", name: "St. Pölten (Land)" },
      { slug: "scheibbs", name: "Scheibbs" },
      { slug: "tulln", name: "Tulln" },
      { slug: "waidhofen-an-der-thaya", name: "Waidhofen an der Thaya" },
      { slug: "wiener-neustadt-land", name: "Wiener Neustadt (Land)" },
      { slug: "zwettl", name: "Zwettl" },
    ],
  },
  {
    slug: "oberoesterreich",
    name: "Oberösterreich",
    country: "at",
    kreise: [
      { slug: "linz-stadt", name: "Linz (Stadt)" },
      { slug: "steyr-stadt", name: "Steyr (Stadt)" },
      { slug: "wels-stadt", name: "Wels (Stadt)" },
      { slug: "braunau-am-inn", name: "Braunau am Inn" },
      { slug: "eferding", name: "Eferding" },
      { slug: "freistadt", name: "Freistadt" },
      { slug: "gmunden", name: "Gmunden" },
      { slug: "grieskirchen", name: "Grieskirchen" },
      { slug: "kirchdorf-an-der-krems", name: "Kirchdorf an der Krems" },
      { slug: "linz-land", name: "Linz-Land" },
      { slug: "perg", name: "Perg" },
      { slug: "ried-im-innkreis", name: "Ried im Innkreis" },
      { slug: "rohrbach", name: "Rohrbach" },
      { slug: "schaerding", name: "Schärding" },
      { slug: "steyr-land", name: "Steyr-Land" },
      { slug: "urfahr-umgebung", name: "Urfahr-Umgebung" },
      { slug: "voecklabruck", name: "Vöcklabruck" },
      { slug: "wels-land", name: "Wels-Land" },
    ],
  },
  {
    slug: "steiermark",
    name: "Steiermark",
    country: "at",
    kreise: [
      { slug: "graz-stadt", name: "Graz (Stadt)" },
      { slug: "bruck-muerzzuschlag", name: "Bruck-Mürzzuschlag" },
      { slug: "deutschlandsberg", name: "Deutschlandsberg" },
      { slug: "graz-umgebung", name: "Graz-Umgebung" },
      { slug: "hartberg-fuerstenfeld", name: "Hartberg-Fürstenfeld" },
      { slug: "leibnitz", name: "Leibnitz" },
      { slug: "leoben", name: "Leoben" },
      { slug: "liezen", name: "Liezen" },
      { slug: "murau", name: "Murau" },
      { slug: "murtal", name: "Murtal" },
      { slug: "suedoststeiermark", name: "Südoststeiermark" },
      { slug: "voitsberg", name: "Voitsberg" },
      { slug: "weiz", name: "Weiz" },
    ],
  },
  {
    slug: "tirol",
    name: "Tirol",
    country: "at",
    kreise: [
      { slug: "innsbruck-stadt", name: "Innsbruck (Stadt)" },
      { slug: "imst", name: "Imst" },
      { slug: "innsbruck-land", name: "Innsbruck-Land" },
      { slug: "kitzbuehel", name: "Kitzbühel" },
      { slug: "kufstein", name: "Kufstein" },
      { slug: "landeck", name: "Landeck" },
      { slug: "lienz", name: "Lienz" },
      { slug: "reutte", name: "Reutte" },
      { slug: "schwaz", name: "Schwaz" },
    ],
  },
  {
    slug: "kaernten",
    name: "Kärnten",
    country: "at",
    kreise: [
      { slug: "klagenfurt-stadt", name: "Klagenfurt (Stadt)" },
      { slug: "villach-stadt", name: "Villach (Stadt)" },
      { slug: "feldkirchen", name: "Feldkirchen" },
      { slug: "hermagor", name: "Hermagor" },
      { slug: "klagenfurt-land", name: "Klagenfurt-Land" },
      { slug: "st-veit-an-der-glan", name: "St. Veit an der Glan" },
      { slug: "spittal-an-der-drau", name: "Spittal an der Drau" },
      { slug: "villach-land", name: "Villach-Land" },
      { slug: "voelkermarkt", name: "Völkermarkt" },
      { slug: "wolfsberg", name: "Wolfsberg" },
    ],
  },
  {
    slug: "salzburg",
    name: "Salzburg",
    country: "at",
    kreise: [
      { slug: "salzburg-stadt", name: "Salzburg (Stadt)" },
      { slug: "hallein", name: "Hallein" },
      { slug: "salzburg-umgebung", name: "Salzburg-Umgebung" },
      { slug: "st-johann-im-pongau", name: "St. Johann im Pongau" },
      { slug: "tamsweg", name: "Tamsweg" },
      { slug: "zell-am-see", name: "Zell am See" },
    ],
  },
  {
    slug: "vorarlberg",
    name: "Vorarlberg",
    country: "at",
    kreise: [
      { slug: "bregenz", name: "Bregenz" },
      { slug: "bludenz", name: "Bludenz" },
      { slug: "dornbirn", name: "Dornbirn" },
      { slug: "feldkirch", name: "Feldkirch" },
    ],
  },
  {
    slug: "burgenland",
    name: "Burgenland",
    country: "at",
    kreise: [
      { slug: "eisenstadt-stadt", name: "Eisenstadt (Stadt)" },
      { slug: "rust-stadt", name: "Rust (Stadt)" },
      { slug: "eisenstadt-umgebung", name: "Eisenstadt-Umgebung" },
      { slug: "guessing", name: "Güssing" },
      { slug: "jennersdorf", name: "Jennersdorf" },
      { slug: "mattersburg", name: "Mattersburg" },
      { slug: "neusiedl-am-see", name: "Neusiedl am See" },
      { slug: "oberpullendorf", name: "Oberpullendorf" },
      { slug: "oberwart", name: "Oberwart" },
    ],
  },
  {
    slug: "zuerich",
    name: "Zürich",
    country: "ch",
    kreise: [
      { slug: "affoltern", name: "Affoltern" },
      { slug: "andelfingen", name: "Andelfingen" },
      { slug: "buelach", name: "Bülach" },
      { slug: "dielsdorf", name: "Dielsdorf" },
      { slug: "dietikon", name: "Dietikon" },
      { slug: "hinwil", name: "Hinwil" },
      { slug: "horgen", name: "Horgen" },
      { slug: "meilen", name: "Meilen" },
      { slug: "pfaeffikon", name: "Pfäffikon" },
      { slug: "uster", name: "Uster" },
      { slug: "winterthur", name: "Winterthur" },
      { slug: "zuerich-bezirk", name: "Zürich" },
    ],
  },
  {
    slug: "bern",
    name: "Bern",
    country: "ch",
    kreise: [
      { slug: "bern-mittelland", name: "Bern-Mittelland" },
      { slug: "biel-bienne", name: "Biel/Bienne" },
      { slug: "emmental", name: "Emmental" },
      { slug: "frutigen-niedersimmental", name: "Frutigen-Niedersimmental" },
      { slug: "interlaken-oberhasli", name: "Interlaken-Oberhasli" },
      { slug: "jura-bernois", name: "Jura bernois" },
      { slug: "oberaargau", name: "Oberaargau" },
      { slug: "obersimmental-saanen", name: "Obersimmental-Saanen" },
      { slug: "seeland", name: "Seeland" },
      { slug: "thun", name: "Thun" },
    ],
  },
  {
    slug: "luzern",
    name: "Luzern",
    country: "ch",
    kreise: [
      { slug: "luzern-bezirk", name: "Luzern" },
      { slug: "hochdorf", name: "Hochdorf" },
      { slug: "sursee", name: "Sursee" },
      { slug: "willisau", name: "Willisau" },
      { slug: "entlebuch", name: "Entlebuch" },
    ],
  },
  {
    slug: "uri",
    name: "Uri",
    country: "ch",
    kreise: [],
  },
  {
    slug: "schwyz",
    name: "Schwyz",
    country: "ch",
    kreise: [
      { slug: "einsiedeln", name: "Einsiedeln" },
      { slug: "gersau", name: "Gersau" },
      { slug: "hoefe", name: "Höfe" },
      { slug: "kuessnacht", name: "Küssnacht" },
      { slug: "march", name: "March" },
      { slug: "schwyz-bezirk", name: "Schwyz" },
    ],
  },
  {
    slug: "obwalden",
    name: "Obwalden",
    country: "ch",
    kreise: [],
  },
  {
    slug: "nidwalden",
    name: "Nidwalden",
    country: "ch",
    kreise: [],
  },
  {
    slug: "glarus",
    name: "Glarus",
    country: "ch",
    kreise: [],
  },
  {
    slug: "zug",
    name: "Zug",
    country: "ch",
    kreise: [],
  },
  {
    slug: "freiburg",
    name: "Freiburg",
    country: "ch",
    kreise: [
      { slug: "broye", name: "Broye" },
      { slug: "glane", name: "Glâne" },
      { slug: "greyerz", name: "Greyerz" },
      { slug: "see", name: "See" },
      { slug: "saane", name: "Saane" },
      { slug: "sense", name: "Sense" },
      { slug: "vivisbach", name: "Vivisbach" },
    ],
  },
  {
    slug: "solothurn",
    name: "Solothurn",
    country: "ch",
    kreise: [
      { slug: "bucheggberg", name: "Bucheggberg" },
      { slug: "dorneck", name: "Dorneck" },
      { slug: "gaeu", name: "Gäu" },
      { slug: "goesgen", name: "Gösgen" },
      { slug: "lebern", name: "Lebern" },
      { slug: "olten", name: "Olten" },
      { slug: "solothurn-bezirk", name: "Solothurn" },
      { slug: "thal", name: "Thal" },
      { slug: "thierstein", name: "Thierstein" },
      { slug: "wasseramt", name: "Wasseramt" },
    ],
  },
  {
    slug: "basel-stadt",
    name: "Basel-Stadt",
    country: "ch",
    kreise: [],
  },
  {
    slug: "basel-landschaft",
    name: "Basel-Landschaft",
    country: "ch",
    kreise: [
      { slug: "arlesheim", name: "Arlesheim" },
      { slug: "laufen", name: "Laufen" },
      { slug: "liestal", name: "Liestal" },
      { slug: "sissach", name: "Sissach" },
      { slug: "waldenburg", name: "Waldenburg" },
    ],
  },
  {
    slug: "schaffhausen",
    name: "Schaffhausen",
    country: "ch",
    kreise: [],
  },
  {
    slug: "appenzell-ausserrhoden",
    name: "Appenzell Ausserrhoden",
    country: "ch",
    kreise: [],
  },
  {
    slug: "appenzell-innerrhoden",
    name: "Appenzell Innerrhoden",
    country: "ch",
    kreise: [],
  },
  {
    slug: "st-gallen",
    name: "St. Gallen",
    country: "ch",
    kreise: [
      { slug: "rheintal", name: "Rheintal" },
      { slug: "rorschach", name: "Rorschach" },
      { slug: "st-gallen-bezirk", name: "St. Gallen" },
      { slug: "toggenburg", name: "Toggenburg" },
      { slug: "werdenberg", name: "Werdenberg" },
      { slug: "wil", name: "Wil" },
      { slug: "sarganserland", name: "Sarganserland" },
      { slug: "see-gaster", name: "See-Gaster" },
    ],
  },
  {
    slug: "graubuenden",
    name: "Graubünden",
    country: "ch",
    kreise: [
      { slug: "albula", name: "Albula" },
      { slug: "bernina", name: "Bernina" },
      {
        slug: "engiadina-bassa-val-muestair",
        name: "Engiadina Bassa/Val Müstair",
      },
      { slug: "imboden", name: "Imboden" },
      { slug: "landquart", name: "Landquart" },
      { slug: "maloja", name: "Maloja" },
      { slug: "moesa", name: "Moesa" },
      { slug: "plessur", name: "Plessur" },
      { slug: "praettigau-davos", name: "Prättigau/Davos" },
      { slug: "surselva", name: "Surselva" },
      { slug: "viamala", name: "Viamala" },
    ],
  },
  {
    slug: "aargau",
    name: "Aargau",
    country: "ch",
    kreise: [
      { slug: "aarau", name: "Aarau" },
      { slug: "baden-aargau", name: "Baden" },
      { slug: "bremgarten", name: "Bremgarten" },
      { slug: "brugg", name: "Brugg" },
      { slug: "kulm", name: "Kulm" },
      { slug: "laufenburg", name: "Laufenburg" },
      { slug: "lenzburg", name: "Lenzburg" },
      { slug: "muri", name: "Muri" },
      { slug: "rheinfelden", name: "Rheinfelden" },
      { slug: "zofingen", name: "Zofingen" },
      { slug: "zurzach", name: "Zurzach" },
    ],
  },
  {
    slug: "thurgau",
    name: "Thurgau",
    country: "ch",
    kreise: [
      { slug: "arbon", name: "Arbon" },
      { slug: "frauenfeld", name: "Frauenfeld" },
      { slug: "kreuzlingen", name: "Kreuzlingen" },
      { slug: "muenchwilen", name: "Münchwilen" },
      { slug: "weinfelden", name: "Weinfelden" },
    ],
  },
  {
    slug: "tessin",
    name: "Tessin",
    country: "ch",
    kreise: [
      { slug: "bellinzona", name: "Bellinzona" },
      { slug: "blenio", name: "Blenio" },
      { slug: "leventina", name: "Leventina" },
      { slug: "locarno", name: "Locarno" },
      { slug: "lugano", name: "Lugano" },
      { slug: "mendrisio", name: "Mendrisio" },
      { slug: "riviera", name: "Riviera" },
      { slug: "vallemaggia", name: "Vallemaggia" },
    ],
  },
  {
    slug: "waadt",
    name: "Waadt",
    country: "ch",
    kreise: [
      { slug: "aigle", name: "Aigle" },
      { slug: "broye-vully", name: "Broye-Vully" },
      { slug: "gros-de-vaud", name: "Gros-de-Vaud" },
      { slug: "jura-nord-vaudois", name: "Jura-Nord vaudois" },
      { slug: "lausanne", name: "Lausanne" },
      { slug: "lavaux-oron", name: "Lavaux-Oron" },
      { slug: "morges", name: "Morges" },
      { slug: "nyon", name: "Nyon" },
      { slug: "ouest-lausannois", name: "Ouest lausannois" },
      { slug: "riviera-pays-d-enhaut", name: "Riviera-Pays-d'Enhaut" },
    ],
  },
  {
    slug: "wallis",
    name: "Wallis",
    country: "ch",
    kreise: [
      { slug: "brig", name: "Brig" },
      { slug: "conthey", name: "Conthey" },
      { slug: "entremont", name: "Entremont" },
      { slug: "goms", name: "Goms" },
      { slug: "herens", name: "Hérens" },
      { slug: "leuk", name: "Leuk" },
      { slug: "martigny", name: "Martigny" },
      { slug: "monthey", name: "Monthey" },
      { slug: "raron", name: "Raron" },
      { slug: "sierre", name: "Sierre" },
      { slug: "sion", name: "Sion" },
      { slug: "st-maurice", name: "St. Maurice" },
      { slug: "visp", name: "Visp" },
    ],
  },
  {
    slug: "neuenburg",
    name: "Neuenburg",
    country: "ch",
    kreise: [],
  },
  {
    slug: "genf",
    name: "Genf",
    country: "ch",
    kreise: [],
  },
  {
    slug: "jura",
    name: "Jura",
    country: "ch",
    kreise: [
      { slug: "delemont", name: "Delémont" },
      { slug: "porrentruy", name: "Porrentruy" },
      { slug: "franches-montagnes", name: "Franches-Montagnes" },
    ],
  },
];

export const PARTY_ART_EXTRA_SEED: Array<{ slug: string; name: string }> = [
  { slug: "dorffeste", name: "Dorffest" },
  { slug: "sonstiges", name: "Sonstiges" },
];
